spring:
  application:
    name: inventario

  data:
    mongodb:
      host: localhost
      port: 27017
      database: inventario-db
      auto-index-creation: true

  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

logging:
  pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tryItOutEnabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
